language: android
android:
  components:
    - build-tools-30.0.3
    - android-30
    - android-21
    - add-on
    - extra
    - platform-tools
    - tools
    - extra-google-googleplayservices
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-28
    - sys-img-armeabi-v7a-android-21
before_install:
  - yes | sdkmanager "platforms;android-30"
script: ./gradlew :app:build

notifications:
  email:
  recipients:
    - bmate711@gmail.com
  on_success: always
  on_failure: always